projects:
  AppSync Rackspace:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: jan6mofzdvh4zbrx6rcyzinmce
        maxDepth: 5
extensions:
  amplify:
    version: 3
